const mongoose=require('mongoose');

const msgSchema=new mongoose.Schema({
    email:{
        type:String,
        require:true,
    },
    name:{
        type:String,
        require:true,
        unique:true
    },
    age:{
        type:Number,
        require:true,
    },
    dob:{
        type:Number,
        require:true,
    },
    gender:{
        type:String,
        require:true,
    },
    mobile:{
        type:Number,
        require:true,
    },
    district:{
        type:String,
        require:true,
    },
    state:{
        type:String,
        require:true,
    },
    country:{
        type:String,
        require:true,
    },
    scholarcategory:{
        type:String,
        require:true,
    },
    address:{
        type:String,
        require:true,
    },
    bankname:{
        type:String,
        require:true,
    },
    branch:{
        type:String,
        require:true,
    },
    aadhar:{
        type:Number,
        require:true,
    },
    accountnumber:{
        type:String,
        require:true,
    },
    college:{
        type:String,
        require:true,
    },
    degree:{
        type:String,
        require:true,
    },
    cgp:{
        type:Number,
        require:true,
    },
    income:{
        type:Number,
        require:true,
    },
    other:{
        type:String,
        require:true,
    },

})
//create model
const Message=new mongoose.model("MESSAGE",msgSchema);
module.exports=Message;